[project]
name = "flowtm"
version = "0.1.0"
description = "Proyecto que propone mejorar GTFS de Transmilenio usando agentes de Inteligencia Artificial. Hecho para la asignatura de Inteligencia Artificial"
readme = "README.md"
license = "GPL-3.0-or-later AND CC-BY-4.0"
license-files = ["LICENSE", "LICENSE-2"]
authors = [
{ name = "Ludwig Alvarado (TheLudway)", email = "me@ludwigalvarado.me" },
{ name = "Kevin Adrian Pinilla Naranjo (KevinAPN)", email = "kevina.pinillan@utadeo.edu.co" },
{ name = "Albert Geovanny Mahecha Reyes (mahecha08)", email = "albertg.mahechar@utadeo.edu.co"  },
{ name = "Maria Fernanda Ospina Rocha (mf-ospina)", email ="m-ospina@utadeo.edu.co" }
]
requires-python = ">=3.9"
dependencies = [
    "marimo>=0.17.6",
    "polars>=1.36.1",
    "ruff>=0.16.4",
]

[project.scripts]
flowtm = "flowtm:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
